# Generated by Django 5.1 on 2024-09-16 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_clone", "0005_twist_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="twist",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="twists_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="twist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="twits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
