# Generated by Django 5.1 on 2024-09-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_clone", "0006_alter_twist_likes_alter_twist_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
