# Generated by Django 5.1 on 2024-09-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter_clone", "0007_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_background",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
